site_name: Space Expansion Manager API
site_url: https://sep.fdu.su/getting_started
repo_url: https://github.com/KakushiTLG/SpaceExpansionManager_Docs

nav:
  - 'index.md'
  - 'base_methods.md'
  - 'profile.md'
  - 'workers.md'
  - 'Вернуться на сайт': 'https://sep.fdu.su/'
  - 'Интерактивная документация': 'https://sep.fdu.su/redoc'
  - 'Contact (Telegram)': 'https://t.me/kakushigoto'

theme:
  language: ru
  name: material
  palette:
    - scheme: slate
      toggle:
        icon: material/lightbulb

    - scheme: default
      toggle:
        icon: material/lightbulb-outline


copyright: >
  Copyright &copy; FDU.SU

## TODO explorations template
## TODO rockets template
